### ISSUE TITLE
Please submit this to cppzmq!

### ISSUE THREAD

**Issue by egpbos** [brettviren/cppzmq-tour#3]
This is an amazing guide and I think it should be included in cppzmq as the official documentation, seeing as currently there is no documentation at all. Did you consider this? Do you have time to contribute? Is there anything I can do to help? Note: I'm not affiliated with ZeroMQ, I'm just a user and have contributed a few small things to cppzmq and libzmq before.

**Comment by brettviren** [comment]
Hi @egpbos 

Thanks!  I am definitely for doing that somehow.  There was a thread on this a while ago 

https://lists.zeromq.org/pipermail/zeromq-dev/2020-April/033322.html 

At the end of that thread:

https://lists.zeromq.org/pipermail/zeromq-dev/2020-April/033328.html

I suggested a few ways to contribute it but got no response and I guess I eventually forgot about it.

I don't have any access under the zeromq GH org so I feel like someone who does needs to do something.  Do you have suggestions on what action to take to make something happen?

**Comment by egpbos** [comment]
I opened a PR for the most minimal suggestion :) https://github.com/zeromq/cppzmq/pull/524 Perhaps this also gets some discussion going, let's see.

**Comment by brettviren** [comment]
Thanks for your action, @egpbos !

I see your PR got merged so there is now a link from https://github.com/zeromq/cppzmq/blob/master/README.md

**Comment by egpbos** [comment]
I guess that closes this issue :) Thanks for your work on this guide, it's really helpful.
